// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208211542_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Collections.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Collections.CollectionAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<int?>("SubGenreId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("GenreId");

                    b.HasIndex("SubGenreId");

                    b.ToTable("CollectionAlbums");
                });

            modelBuilder.Entity("Collections.FavouriteSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionAlbumId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionAlbumId");

                    b.ToTable("FavouriteSongs");
                });

            modelBuilder.Entity("Genres.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pop & Mainstream"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Elektronisk musik"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hip hop & R&B"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jazz & Blues"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Folkmusik & Världsmusik"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Klassiskt"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Övrigt / Nisch"
                        });
                });

            modelBuilder.Entity("Genres.SubGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("SubGenres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 1,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 1,
                            Name = "Indie pop"
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 1,
                            Name = "Synthpop"
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 1,
                            Name = "K-pop"
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 1,
                            Name = "Schlager"
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 2,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 2,
                            Name = "Hårdrock"
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 2,
                            Name = "Alternativ rock"
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 2,
                            Name = "Punk rock"
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 2,
                            Name = "Progressiv rock"
                        },
                        new
                        {
                            Id = 11,
                            GenreId = 2,
                            Name = "Psykedelisk rock"
                        },
                        new
                        {
                            Id = 12,
                            GenreId = 3,
                            Name = "Heavy metal"
                        },
                        new
                        {
                            Id = 13,
                            GenreId = 3,
                            Name = "Death metal"
                        },
                        new
                        {
                            Id = 14,
                            GenreId = 3,
                            Name = "Black metal"
                        },
                        new
                        {
                            Id = 15,
                            GenreId = 3,
                            Name = "Power metal"
                        },
                        new
                        {
                            Id = 16,
                            GenreId = 3,
                            Name = "Doom metal"
                        },
                        new
                        {
                            Id = 17,
                            GenreId = 3,
                            Name = "Metalcore"
                        },
                        new
                        {
                            Id = 18,
                            GenreId = 4,
                            Name = "House"
                        },
                        new
                        {
                            Id = 19,
                            GenreId = 4,
                            Name = "Techno"
                        },
                        new
                        {
                            Id = 20,
                            GenreId = 4,
                            Name = "Trance"
                        },
                        new
                        {
                            Id = 21,
                            GenreId = 4,
                            Name = "Drum and bass"
                        },
                        new
                        {
                            Id = 22,
                            GenreId = 4,
                            Name = "Dubstep"
                        },
                        new
                        {
                            Id = 23,
                            GenreId = 4,
                            Name = "Ambient"
                        },
                        new
                        {
                            Id = 24,
                            GenreId = 5,
                            Name = "Hip hop"
                        },
                        new
                        {
                            Id = 25,
                            GenreId = 5,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 26,
                            GenreId = 5,
                            Name = "Trap"
                        },
                        new
                        {
                            Id = 27,
                            GenreId = 5,
                            Name = "R&B"
                        },
                        new
                        {
                            Id = 28,
                            GenreId = 5,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = 29,
                            GenreId = 5,
                            Name = "Neo-soul"
                        },
                        new
                        {
                            Id = 30,
                            GenreId = 6,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 31,
                            GenreId = 6,
                            Name = "Bebop"
                        },
                        new
                        {
                            Id = 32,
                            GenreId = 6,
                            Name = "Swing"
                        },
                        new
                        {
                            Id = 33,
                            GenreId = 6,
                            Name = "Fusion"
                        },
                        new
                        {
                            Id = 34,
                            GenreId = 6,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 35,
                            GenreId = 7,
                            Name = "Folkmusik"
                        },
                        new
                        {
                            Id = 36,
                            GenreId = 7,
                            Name = "Country"
                        },
                        new
                        {
                            Id = 37,
                            GenreId = 7,
                            Name = "Bluegrass"
                        },
                        new
                        {
                            Id = 38,
                            GenreId = 7,
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = 39,
                            GenreId = 7,
                            Name = "Salsa"
                        },
                        new
                        {
                            Id = 40,
                            GenreId = 7,
                            Name = "Afrobeat"
                        },
                        new
                        {
                            Id = 41,
                            GenreId = 8,
                            Name = "Klassisk musik"
                        },
                        new
                        {
                            Id = 42,
                            GenreId = 8,
                            Name = "Barock"
                        },
                        new
                        {
                            Id = 43,
                            GenreId = 8,
                            Name = "Romantik"
                        },
                        new
                        {
                            Id = 44,
                            GenreId = 8,
                            Name = "Opera"
                        },
                        new
                        {
                            Id = 45,
                            GenreId = 8,
                            Name = "Kammarmusik"
                        },
                        new
                        {
                            Id = 46,
                            GenreId = 9,
                            Name = "Soundtrack/filmmusik"
                        },
                        new
                        {
                            Id = 47,
                            GenreId = 9,
                            Name = "Lo-fi"
                        },
                        new
                        {
                            Id = 48,
                            GenreId = 9,
                            Name = "Chiptune"
                        },
                        new
                        {
                            Id = 49,
                            GenreId = 9,
                            Name = "New age"
                        },
                        new
                        {
                            Id = 50,
                            GenreId = 9,
                            Name = "Post-rock"
                        },
                        new
                        {
                            Id = 51,
                            GenreId = 9,
                            Name = "Experimental"
                        });
                });

            modelBuilder.Entity("Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Collections.Collection", b =>
                {
                    b.HasOne("Users.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Collections.CollectionAlbum", b =>
                {
                    b.HasOne("Collections.Collection", "Collection")
                        .WithMany("Albums")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Genres.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.HasOne("Genres.SubGenre", "SubGenre")
                        .WithMany()
                        .HasForeignKey("SubGenreId");

                    b.Navigation("Collection");

                    b.Navigation("Genre");

                    b.Navigation("SubGenre");
                });

            modelBuilder.Entity("Collections.FavouriteSong", b =>
                {
                    b.HasOne("Collections.CollectionAlbum", "CollectionAlbum")
                        .WithMany("FavouriteSongs")
                        .HasForeignKey("CollectionAlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionAlbum");
                });

            modelBuilder.Entity("Genres.SubGenre", b =>
                {
                    b.HasOne("Genres.Genre", "Genre")
                        .WithMany("SubGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Collections.Collection", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("Collections.CollectionAlbum", b =>
                {
                    b.Navigation("FavouriteSongs");
                });

            modelBuilder.Entity("Genres.Genre", b =>
                {
                    b.Navigation("SubGenres");
                });

            modelBuilder.Entity("Users.User", b =>
                {
                    b.Navigation("Collections");
                });
#pragma warning restore 612, 618
        }
    }
}
